


POST https://demo.bytebase.com/v1/auth/login

{
  "email": "ci@service.bytebase.com",
  "password": "bbs_iqysPHMqhNpG4rQ5SFEJ"
}

POST https://demo.bytebase.com/v1/auth/login

{
  "email": "api@service.bytebase.com",
  "password": "bbs"
}